### ISSUE TITLE
Mock with multiple paths does not work 

### ISSUE THREAD

**Issue by matheusfrancisco** [moclojer/moclojer#230]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When you have and route with 2 nested paths, the mock does not work it always return a not found 

### Reproduce the Bug

Run the moclojer with the following mock

### moclojer config

```
# This mock register route: GET /v1/hello/test/:username
- endpoint:
    # Note: the method could be omitted because GET is the default
    method: GET
    path: /v1/hello/test/:username
    response:
      # Note: the status could be omitted because 200 is the default
      status: 200
      headers:
        Content-Type: application/json
      # Note: the body will receive the value passed in the url using the
      # :username placeholder
      body: >
        {
          "hello": "{{path-params.username}}!"
        }

```
### Expected Behavior

It should return the {hello: username}

### Version and environment information

Os: linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by avelino** [comment]
Some test cases were written, and we couldn't replicate the reported behavior, I am closing this issue.
