### ISSUE TITLE
[Documentation] Add documentation to this repository.

### ISSUE THREAD

**Issue by matheusfrancisco** [moclojer/moclojer#66]
We have our docs in another repository which is https://github.com/avelino/avelino.run/blob/main/content/projects/moclojer.md.
We would like to move it to this repository. This way it will be easier to add new information to our doc.

**Comment by avelino** [comment]
https://docs.moclojer.com/
folder: https://github.com/moclojer/moclojer/tree/main/docs
index: [README.md](https://github.com/moclojer/moclojer/blob/main/README.md)
menu: https://github.com/moclojer/moclojer/blob/main/SUMMARY.md
